using UnityEngine;
using UnityEngine.InputSystem;

///<summary>
/// Reads player input from unity's Input system
/// This class is intentionally responsible only for translating hardware
/// input into gameplay friendly values.
/// </summary>

public sealed class PlayerInputReader : MonoBehaviour
{
    private MtaaInputActions _inputActions;

    // <summary>
    /// Current movement input as a normalized 2D direction.
    /// X represents horizontal movement.
    /// Y represents forward/backward movement.
    /// </summary>
    
    public Vector2 MoveInput { get; private set; }

     ///<summary>
    /// Current look input generated by the mouse or other look device.
    /// </summary>
    public Vector2 LookInput { get; private set; }

    private void Awake()
    {
        _inputActions = new MtaaInputActions();

    }

    private void OnEnable()
    {
        _inputActions.Enable();
    }

    private void OnDisable()
    {
        _inputActions.Disable();
    }

    private void Update()
    {
        MoveInput = _inputActions.Player.Move.ReadValue<Vector2>();
        LookInput = _inputActions.Player.Look.ReadValue<Vector2>();
    }
}